version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
      MONGODB_USER: pokemon
      MONGODB_PASSWORD: pokeapi
    volumes:
      - ./mongo:/data/db